services:
  dsd-frontend:
    image: node:alpine
    container_name: dsd-frontend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: sh -c "npm i && npm run build --webpack && npm run start"
